{
 "title": "Pizza Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pizza_creation_latency_ms_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_latency_ms_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(order_success_total{type=\"success\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza Orders"
    },
    {
     "expr": "rate(order_failure_total{type=\"failure\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(auth_success_total{type=\"success\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_failure_total{type=\"failure\", source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "users_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Total Users"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(http_requests_total{method=\"GET\", source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(http_requests_total{method=\"DELETE\", source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(http_requests_total{method=\"POST\", source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(http_requests_total{method=\"PUT\", source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(http_requests_total{method=\"ANY\", source=\"jwt-pizza-service-dev\"}[30s])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Memory Gauge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Guage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}